version: '3.9'

services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"  # 🔥 Now using 3000 instead of 3001
    depends_on:
      - api-gateway
    environment:
      NODE_ENV: production

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "5000:5000"  # API Gateway now uses 5000
    depends_on:
      - pp-auth
      - pp-user
    environment:
      NODE_ENV: production
      GRPC_AUTH_SERVICE_URL: "grpc://pp-auth:50051"
      GRPC_USER_SERVICE_URL: "grpc://pp-user:50052"

  pp-auth:
    build: ./pp-auth
    container_name: pp-auth
    ports:
      - "5001:5001"  # REST API
      - "50051:50051"  # gRPC API
    environment:
      NODE_ENV: production

  pp-user:
    build: ./pp-user
    container_name: pp-user
    ports:
      - "5002:5002"  # REST API
      - "50052:50052"  # gRPC API
    environment:
      NODE_ENV: production